
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5174:8080"
    volumes:
      - ./backend/sounds:/app/sounds
      - ./backend/soundboard.db:/app/soundboard.db
    env_file:
      - ./backend/.env
    restart: unless-stopped
    networks:
      - soundboard-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - soundboard-network
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  discord-bot:
    build:
      context: ./discord_bot
      dockerfile: DockerFile
    depends_on:
      - backend
    env_file:
      - ./discord_bot/.env
    restart: unless-stopped
    networks:
      - soundboard-network
    develop:
      watch:
        - action: rebuild
          path: ./discord_bot

networks:
  soundboard-network:
    driver: bridge

volumes:
  sounds:
  database:
